"""Adiciona tabela Fragment

Revision ID: 808805c07a07
Revises: 0662647d5421
Create Date: 2025-06-04 16:35:21.275534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808805c07a07'
down_revision = '0662647d5421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m_z', sa.Float(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('compound_analytics_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compound_analytics_id'], ['tbl_compound_analytics.analytics_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
#  op.alter_column('tbl_compound', 'pubchem_cid',
#            existing_type=sa.TEXT(),
#               type_=sa.String(length=50),
#               existing_nullable=True)
#    op.alter_column('tbl_compound', 'pubchem_url',
#               existing_type=sa.TEXT(),
#               type_=sa.String(length=255),
#               existing_nullable=True)
#    op.alter_column('tbl_compound_analytics', 'analytics_id',
#               existing_type=sa.INTEGER(),
#               nullable=False,
#               autoincrement=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_compound_analytics', 'analytics_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('tbl_compound', 'pubchem_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tbl_compound', 'pubchem_cid',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('fragments')
    # ### end Alembic commands ###
