"""Cria tbl_compound_analytics

Revision ID: 815eacd1bd8b
Revises: 
Create Date: 2025-04-11 11:45:25.563516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815eacd1bd8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_compound_analytics',
    sa.Column('analytics_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=True),
    sa.Column('retention_time', sa.Float(), nullable=True),
    sa.Column('m_z', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('instrument_method', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['tbl_compound.compound_id'], ),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_compound_analytics')
    # ### end Alembic commands ###
